/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sorting;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sergio
 */
public class SortingView extends javax.swing.JFrame {

    /**
     * Creates new form SortingView
     */
    public SortingView() {
        initComponents();
        
        modelo = (DefaultTableModel) tblAlumnos.getModel();
        agregarDatos();
    }
    public void limpiar() {
        for (int i = 0; i < tblAlumnos.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }
    public void agregarDatos() {
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;
        try {
            archivo = new File("Alumnos/Alumnos.txt");
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);
            System.out.println("Leyendo el contendio del archivo.txt");
            String linea;
            int i=0;
            B=new Alumno[40];
            while ((linea = br.readLine()) != null) {
                String[] parts = linea.split("-");
                C = new Materia(parts[2], parts[3], parts[4], parts[5], parts[6]);
                A = new Alumno(parts[0], parts[7], C, Integer.parseInt(parts[1]));
                B[i]=A;
                AñadirTabla(A);
                i++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (null != fr) {
                    fr.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
    }
    public void AñadirTabla(Alumno D) {
        Object T[] = new Object[9];
        T[0] = D.getNombre();
        T[1] = D.getEdad();
        T[2] = D.getNumC();
        T[3] = D.getMat().getUnidad1();
        T[4] = D.getMat().getUnidad2();
        T[5] = D.getMat().getUnidad3();
        T[6] = D.getMat().getUnidad4();
        T[7] = D.getMat().getUnidad5();
        T[8] = D.getMat().getProm();
        modelo.addRow(T);
        
    }
    public void divArreglo(Alumno X[]){
        F=new Alumno[X.length/2];
        G=new Alumno[X.length/2];
        for(int i=0;i<X.length/2;i++){
            F[i]=X[i];
        }
        for(int j=20;j<X.length;j++){
            G[j-20]=X[j];
        }
    }
    public void rehacer(Alumno Y[]){
        limpiar();
        System.out.println("aaa");
        limpiar();
        for(int i=0;i<Y.length;i++){
            AñadirTabla(Y[i]);
        }
    }
    public void verAlumno(Alumno temp){
        Alumnos form=new Alumnos();
        form.Stablish(temp);
        form.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblMerge = new javax.swing.JLabel();
        lblInter = new javax.swing.JLabel();
        lblShell = new javax.swing.JLabel();
        lblRadix = new javax.swing.JLabel();
        lblQuick = new javax.swing.JLabel();
        lblBubble = new javax.swing.JLabel();
        cmbOrdena = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        lblBusqSec = new javax.swing.JLabel();
        lblBusqBin = new javax.swing.JLabel();
        lblBusqHash = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordenacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        lblMerge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Merge.png"))); // NOI18N
        lblMerge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMergeMouseClicked(evt);
            }
        });

        lblInter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intercalacion.png"))); // NOI18N
        lblInter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInterMouseClicked(evt);
            }
        });

        lblShell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/shellsort.png"))); // NOI18N
        lblShell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShellMouseClicked(evt);
            }
        });

        lblRadix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/radix.png"))); // NOI18N
        lblRadix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRadixMouseClicked(evt);
            }
        });

        lblQuick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Quicksort.png"))); // NOI18N
        lblQuick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuickMouseClicked(evt);
            }
        });

        lblBubble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bubble.png"))); // NOI18N
        lblBubble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBubbleMouseClicked(evt);
            }
        });

        cmbOrdena.setBackground(new java.awt.Color(255, 255, 255));
        cmbOrdena.setForeground(new java.awt.Color(0, 0, 0));
        cmbOrdena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Criterio de Ordenación", "Nombre", "Edad", "No.Ctrl", "Prom" }));
        cmbOrdena.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblBubble)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cmbOrdena, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblMerge)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(lblInter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRadix)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblQuick)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblShell)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbOrdena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBubble)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRadix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMerge))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField2.setText("jTextField2");

        lblBusqSec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Secuencial.png"))); // NOI18N
        lblBusqSec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBusqSecMouseClicked(evt);
            }
        });

        lblBusqBin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Binaria.png"))); // NOI18N

        lblBusqHash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hash.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTextField2)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBusqBin)
                    .addComponent(lblBusqSec)
                    .addComponent(lblBusqHash))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBusqSec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBusqBin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBusqHash)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "No. Control", "Unidad 1", "Unidad 2", "Unidad 3", "Unidad 4", "Unidad 5", "Promedio"
            }
        ));
        tblAlumnos.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tblAlumnos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBubbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBubbleMouseClicked
        int a=cmbOrdena.getSelectedIndex();
        Alumno C[]=S.BubbleSort(B, S.opcion(a));
        rehacer(C);
    }//GEN-LAST:event_lblBubbleMouseClicked

    private void lblRadixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRadixMouseClicked
        int a=cmbOrdena.getSelectedIndex();
        Alumno C[]=S.radixSort(B,S.opcion(a));
        rehacer(C);
    }//GEN-LAST:event_lblRadixMouseClicked

    private void lblQuickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuickMouseClicked
        int a=cmbOrdena.getSelectedIndex();
        Alumno C[]=S.QuickSort(B,0, B.length-1, S.opcion(a));
        rehacer(C);
    }//GEN-LAST:event_lblQuickMouseClicked

    private void lblInterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInterMouseClicked
        int a=cmbOrdena.getSelectedIndex();
        Alumno X[]=S.BubbleSort(B,S.opcion(a));
        divArreglo(X);
        Alumno aux[]=S.Intercalacion(F, G);
        rehacer(aux);
    }//GEN-LAST:event_lblInterMouseClicked

    private void lblShellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShellMouseClicked
        int a=cmbOrdena.getSelectedIndex();
        Alumno C[]=S.shellSort(B, S.opcion(a));
        rehacer(C);
    }//GEN-LAST:event_lblShellMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked

    }//GEN-LAST:event_jPanel4MouseClicked

    private void lblMergeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMergeMouseClicked
        int a=cmbOrdena.getSelectedIndex();
        Alumno C[]=S.Mezcla(B,S.opcion(a));
        rehacer(C);
    }//GEN-LAST:event_lblMergeMouseClicked

    private void lblBusqSecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBusqSecMouseClicked
       int pos=SE.Bin(B,"16400944");
       showMessageDialog(null,pos);
       verAlumno(B[pos]);
    }//GEN-LAST:event_lblBusqSecMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortingView().setVisible(true);
            }
        });
    }
    private Alumno A = new Alumno(),B[],F[],G[],H[];
    private Materia C = new Materia();
    private Sorting S=new Sorting(40);
    private Search SE=new Search();
    private DefaultTableModel modelo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOrdena;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblBubble;
    private javax.swing.JLabel lblBusqBin;
    private javax.swing.JLabel lblBusqHash;
    private javax.swing.JLabel lblBusqSec;
    private javax.swing.JLabel lblInter;
    private javax.swing.JLabel lblMerge;
    private javax.swing.JLabel lblQuick;
    private javax.swing.JLabel lblRadix;
    private javax.swing.JLabel lblShell;
    private javax.swing.JTable tblAlumnos;
    // End of variables declaration//GEN-END:variables
}
